name: ticktag_mobile
description: "A new Flutter project."

publish_to: 'none' # Mantém o pacote privado

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/logo_dark.png
    - assets/logo_light.png

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_dark.png"
